site_name: Lamden Develop Tools
theme: readthedocs
nav:
    - Lamden Vault API:
      - Overview: /wallet_api/overview
      - Create Wallet Connection: /wallet_api/create_connection
      - Customize Connection: /wallet_api/customize_connection
      - Get Account Info: /wallet_api/get_wallet_info
      - Submit Transactions: /wallet_api/send_transactions
      - Approval Transactions: /wallet_api/approval_transactions
    - Lamden Vault Controller:
      - Quickstart: /wallet_controller/wallet_controller_quickstart
      - API: /wallet_controller/wallet_controller_api
    - BlockChain:
      - Masternode Information: /blockchain/current_masternodes
      - Masternode REST API: /blockchain/masternode_api
    - Blockservice:
      - Overview:  /blockservice/overview
      - Estimation Script Installation:  /blockservice/estimationScriptInstallation
      - Blockservice Installation:  /blockservice/installation
      - Blockservice Config:  /blockservice/config
      - REST API:  /blockservice/restful
      - Events:  /blockservice/events
    - Languages:
      - Javascript:
        - Lamden-js:
          - Overview:  /lamden_js/overview
          - Wallets:  /lamden_js/wallets
          - Network Object:  /lamden_js/network
          - Transactions:  /lamden_js/transactions
          - Masternode API:  /lamden_js/masternode_api_wrapper
      - C#:
        - Unity 3D Plugin: /unity_3d/unity_3d

