site_name: Lamden Vault
theme: readthedocs
nav:
    - Overview: overview.md
    - Installation: /first_vault_install
    - Quick Start: 
      - Create Vault: /first_vault_create
      - Restore Vault: /first_vault_restore
      - Lock and Unlock: /lock_unlock
    - Key Concepts: 
      - Accounts:
        - Overview: /accounts_overview
        - Creating: /accounts_creation
        - Copy Account Address: /accounts_copy_address
        - Delete: /accounts_delete
      - Linked Accounts:
        - Overview: /accounts_linked_overview
        - Creating: /accounts_linked_create
        - Approve TAU Spending: /accounts_linked_approval
        - Approve Transfers: /accounts_linked_transfer
        - Revoke Access: /accounts_linked_revoke
      - Dapp Connections:
        - Overview: /dapp_connections_overview
        - Change Account: /dapp_connections_change
      - Tokens:
        - Add: /tokens_add_token
        - Edit: /tokens_delete_token
        - Delete: /tokens_edit_token
        - Transfer: /tokens_transfer_token
      - Transactions:
        - Overview: /transactions_overview
        - Create a Transaction: /transactions_create
        - Create An Advanced Transaction: /transactions_advanced_create
        - Transaction Result: /transactions_result
      - Smart Contract IDE:
        - Overview: /ide_overview
        - Create Smartcontract: /ide_create_smartcontracts
        - Submit a Smartcontract: /ide_submit_smartcontract
        - Query and Run: /ide_test_smartcontracts
      - Settings:
        - Bakcup:
          - Overview: /backup_overview
          - View Recovery Phrase: /backup_recovery_phrase
          - Backup Legacy Accounts: /backup_keystore
          - View Accounts Keys: /backup_view_keys
        - Manage Networks:
          - Overview: /network_overview
          - Change Network: /change_network
          - Manage Network: /manage_network